"""
memory/memory_store.py

Persistent memory layer for pipeline-mind.
Stores schema snapshots, column stats, and run history in SQLite.
Every agent reads and writes through here.
"""

import sqlite3
import json
import os
from datetime import datetime, timezone


DB_PATH = os.path.join(os.path.dirname(__file__), "../pipeline_mind.db")

def get_connection():
    conn=sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS runs (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            source        TEXT NOT NULL,
            run_at        TEXT NOT NULL,
            row_count     INTEGER,
            col_count     INTEGER,
            status        TEXT DEFAULT 'started'
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS column_stats (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            run_id        INTEGER NOT NULL,
            col_name      TEXT NOT NULL,
            dtype         TEXT,
            null_count    INTEGER,
            null_rate     REAL,
            unique_count  INTEGER,
            min_val       TEXT,
            max_val       TEXT,
            mean_val      REAL,
            FOREIGN KEY   (run_id) REFERENCES runs(id)
         )
     """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS schema_snapshots (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            run_id      INTEGER NOT NULL,
            snapshot    TEXT NOT NULL,
            FOREIGN KEY(run_id) REFERENCES runs(id)
         )
     """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS reports(
            id          INTEGER PRIMARY KEY AUTOINCREMENT, 
            run_id      INTEGER NOT NULL,
            content     TEXT NOT NULL,
            FOREIGN KEY (run_id) REFERENCES runs(id)
         )
     """)

    conn.commit()
    conn.close()

def start_run(source: str, row_count: int, col_count: int) -> int:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO runs (source, run_at, row_count, col_count, status)
        VALUES (?, ?, ?, ?, 'started')
        """, (source, datetime.now(timezone.utc).isoformat(), row_count, col_count))
    run_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return run_id

def complete_run(run_id: int):
    conn = get_connection()
    cursor= conn.cursor()
    cursor.execute("UPDATE runs SET status = 'completed' WHERE id = ?", (run_id,))
    conn.commit()
    conn.close()

def asve_column_status(run_id: int, stats: list[dict]):
    conn = get_connection()
    cursor = conn.cursor()
    for s in stats:
        cursor.execute("""
            INSERT INTO column_stats
                (run_id, col_nmae, dtype, null_count, null_rate,unique_count, min_val, max_val, mean_val)
                values (?,?,?,?,?,?,?,?)
             """, (
                run_id,
                s.get("col_name"),
                s.get("dtype"),
                s.get("null_count"),
                s.get("null_rate"),
                s.get("unique_count"),
                str(s.get("min_val")),
                str(s.get("max_val")),
                s.get("mean_val"),
        ))
    conn.commit()
    conn.close()


def save_schema_snapshot(run_id: int, schema: dict):
    # Saves schema as JSON string. Called by the Ingestion Agent after reading the dataset.
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
                   INSERT INTO schema_snapshots (run_id, snapshot)
                   VALUES (?, ?)
                   """, (run_id, json.dumps(schema)))
    conn.commit()
    conn.close()


def save_report(run_id: int, content: str):
    # Saves the final report generated by the Report Agent.
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT INTO reports (run_id, content) VALUES (?, ?)", (run_id, content))
    conn.commit()
    conn.close()


def get_previous_run(source: str) -> dict | None:
    # Returns the last completed run for a source. Returns None on first run.
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
                   SELECT *
                   FROM runs
                   WHERE source = ?
                     AND status = 'completed'
                   ORDER BY id DESC LIMIT 1
                   """, (source,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def get_previous_column_stats(run_id: int) -> list[dict]:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM column_stats WHERE run_id = ?", (run_id,))
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_previous_schema(run_id: int) -> dict | None:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT snapshot FROM schema_snapshots WHERE run_id = ?", (run_id,))
    row = cursor.fetchone()
    conn.close()
    return json.loads(row["snapshot"]) if row else None


def get_run_history(source: str, limit: int = 10) -> list[dict]:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
                   SELECT r.id,
                          r.source,
                          r.run_at,
                          r.row_count,
                          r.col_count,
                          rp.content as report
                   FROM runs r
                            LEFT JOIN reports rp ON rp.run_id = r.id
                   WHERE r.source = ?
                     AND r.status = 'completed'
                   ORDER BY r.id DESC LIMIT ?
                   """, (source, limit))
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]



